version: "1.2"
services:
  postgres-db:
    image: postgres:11.2-alpine
    ports:
      - 5344:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - database-postgre:/var/lib/postgresql/data

  app:
    build: 
      context: .
    environment:
      PORT: 3030 
    depends_on:
      - postgres-db
    ports:
      - 3030:3000
    expose:
      - 3030

volumes:
  database-postgre:


