version: "1.0"
services:
  app:
    build: . 
    depends_on:
      - postgres-db
    ports:
      - 3030:3000
    expose:
      - 3030

  postgres-db:
    image: postgres:11.2-alpine
    environment:  
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
